version: '3.8'

services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOG_FORWARD_URL=http://log-forwarder:3100/ingest
    depends_on:
      - log-forwarder

  log-forwarder:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"